import express from "express";
import tripRoutes from "./src/routes/trip-routes.js";
import cors from "cors";
import authRoutes from "./src/routes/auth-routes.js";
const app = express();
app.use(cors({ origin: "http://localhost:5173", credentials: true }));
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ limit: "10mb", extended: true }));
app.use("/uploads", express.static("uploads"));
app.use("/api/trips", tripRoutes);
app.use("/api/auth", authRoutes);
export default app;
